// <auto-generated />
namespace FinalWindow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class nts9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nts9));
        
        string IMigrationMetadata.Id
        {
            get { return "202305171001106_nts9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
